### PR TITLE
Ace editor variable highlighting

### LINKED ISSUE #33: ACE Editor mode
ACE Editor ist im Moment immer Java. Das sollte auch auf die entsprechende Sprache der Files angepasst werden.

### LINKED ISSUE #235: Fix Asset precompilation
Up to now, all assets machine the pattern `'*.js', '*.css', '*.css.erb', '*.coffee', '*.scss'` were precompiled. That yielded an error during deployment after merging #230:

```
Tasks: TOP => deploy:assets:precompile
(See full trace by running task with --trace)
The deploy has failed with an error: Exception while executing as codeharbor@codeharbor.xi.xopic.de: rake exit status: 1
rake stdout: Nothing written
rake stderr: rake aborted!
SassC::SyntaxError: Error: Undefined variable: "$navbar-height".
        on line 16:16 of ../../shared/bundle/ruby/2.6.0/gems/rails_admin-2.0.1/app/assets/stylesheets/rails_admin/base/theming.scss
>>   padding-top: $navbar-height;

   ---------------^
```

This is related to [this issue in rails_admin](https://github.com/sferik/rails_admin/issues/2466) suggesting not to precompile all assets. 

Hence, I disabled that behavior with f378a18 and tested the result in the production environment locally without error. Nevertheless, we should evaluate whether no other assets are required and update `production.rb` accordingly.

### PR DESCRIPTION
**Pull request by kkoehn**
Added automatic switching of editor mode based on selected language.
Added `editor_mode` field to FileType (just like CO), we'll have to fill those - or replant the corresponding seeds.
fixes #33 
fixes #235 

To fix the dynamic reloading of the editor-modes I added a gem called `ace-rails-ap`.
Note that assets:precompile seems to take some time now

### CODE REVIEW

**Comment by MrSerth** [comment]
After deployment: Migrate existing FileTypes

**Comment by MrSerth** [comment]
I talked to my colleagues and no one raised an issue migrating to `ace-rails-ap`.

**Comment by MrSerth** [comment]
Merged, deployed and migrated. Further, I fixed the deployment of assets in the public folder so that these should be served correctly as well. 

I noticed, the test files are not highlighted at all. That would be nice to be fixed. And I wondered that there is a different theme when viewing files (white background) and editing these (dark background).

**Comment by kkoehn** [comment]
> And I wondered that there is a different theme when viewing files (white background) and editing these (dark background).

I saw that as well, but just assumed it was by choice and just kept it that way. I don't really mind

**Comment by MrSerth** [comment]
> > And I wondered that there is a different theme when viewing files (white background) and editing these (dark background).
> 
> I saw that as well, but just assumed it was by choice and just kept it that way. I don't really mind

I don't know either. At least it would not be my choice ;) - I would use the same design for both. Feel free to either suppose something or leave it as it is for now.

**Comment by kkoehn** [comment]
> Do we know whether any modifications were made in the ace files? 

The whole ace-folder got added in one commit 51ed8b54fcbfa21c89bd1a072071f962d865cdee, which makes me believe that is was just copied over.

**Pull request merged**
