### PR TITLE
Clean inline styles within script

### PR DESCRIPTION
**Pull request by zuhrasofyan**
This part is to clean up all remaining dynamic script controlled inline styles

### CODE REVIEW

**Comment by MrSerth** [comment]
I would be grateful if you could perform a rebase (rather than merging the current master).

**Comment by zuhrasofyan** [comment]
Sorry, it was my fault. I accidentally merging and already push it to origin. Now I do not know how to redo the operation...

**Comment by zuhrasofyan** [comment]
I will close this PR. I have created a new branch and cherry-picked the commit from here.

**Comment by MrSerth** [comment]
Alright. While you could have force-pushed to the branch of this PR (which would have updated it), this solution is also doable. Thanks for figuring out a solution.

Please do not forget that I added two comments already [here](https://github.com/openHPI/codeharbor/commit/ae3da626252d98d60c3a6ba2e13d332fb89650d1#r144123525) and [here](https://github.com/openHPI/codeharbor/commit/ae3da626252d98d60c3a6ba2e13d332fb89650d1#r144123530). Once you've seen then, feel free to remove the old branch of this PR.

**Pull request closed without merging**
